#!/bin/bash

#================#
#  Git(gogs)     #
#================#
export APP_DOMAIN=${APP_DOMAIN:-git.demo.com}           # User-defined
export MYSQL_HOST=${MYSQL_HOST:-"127.0.0.1"}
export MYSQL_PORT=${MYSQL_PORT:-"3306"} 
export MYSQL_DB=${MYSQL_DB:-"gogs"} 
export MYSQL_USER=${MYSQL_USER:-"root"} 
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-"pass4Gogs"} 
SECRET_KEY=$(pwgen -ac 16 1) && export SECRET_KEY
export DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME:-"git-admin"}    # User-defined
export DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-"pass4Git"}     # User-defined
export ADMIN_EMAIL=${ADMIN_EMAIL:-"demo@chandao.net"}   # User-defined
export GIT_FORCE_PRIVATE=${GIT_FORCE_PRIVATE:-false}    # User-defined

# ======================#
# Persistence directory #
#=======================#
export PERSISTENCE_LIST="
/data/git
/data/git/data/attachments
/data/git/repositories
/data/git/tmp/uploads
/data/git/https
/data/git/avatars
/data/git/repo-avatars
/data/git/sessions
/data/git/log
/data/git/lfs-objects"
